-- ============================================================================
--  UniManager — COMPLETE DATABASE SCHEMA REFERENCE
--  Project: github.com/andrewleko19-boop/unimanager
--  Supabase project ref: gcjlvfggsupndpnjoake
--  App version this reflects: v1.33.0
-- ----------------------------------------------------------------------------
--  PURPOSE OF THIS FILE
--  This is a REFERENCE / RE-CREATION script describing every table, column,
--  index, and Row-Level-Security (RLS) policy the app depends on. Paste it into
--  a NEW chat (or a fresh Supabase project) so the assistant immediately knows
--  the full data model without having to re-discover it.
--
--  IMPORTANT — READ BEFORE RUNNING
--  • Your LIVE Supabase already has all of this. You do NOT need to run this to
--    keep working. It is documentation + a disaster-recovery / clone script.
--  • Running it on your existing project is SAFE: every statement uses
--    "if not exists" / "create or replace" / idempotent policy drops, so it
--    will not duplicate or destroy data. But you normally won't need to.
--  • The GROUP RPC FUNCTIONS (create_group, join_group_by_code, …) are NOT
--    fully reproduced here because their bodies live only in your Supabase,
--    not in the app code. Their SIGNATURES are listed at the bottom so you/the
--    assistant know they exist. If you ever lose them, ask the assistant to
--    rewrite them from the documented behaviour — do not assume this file
--    recreates them.
--
--  RLS REVIEW FIXES (2026-06-05) — see SECTION 6 at the bottom for the full
--  rationale. Four code-vs-policy conflicts found during an RLS audit are now
--  resolved inline:
--    [FIX 1] group_subject_notes is member-writable (was admin-only) to match
--            the app's "any member edits notes" behaviour.
--    [FIX 2] group_members has a self-DELETE policy so leaveGroup() actually
--            removes the row (it was silently denied before).
--    [FIX 3] member_directory view + shares_group_with() helper expose only
--            (user_id, name, avatar_url) to co-members, so the roster shows
--            real names without leaking the rest of user_settings.
--    [FIX 4] message inserts honour groups.chat_mode='admins' at the DB layer
--            via can_post_in_group(), instead of trusting the UI.
-- ============================================================================


-- ============================================================================
--  SECTION 1 — PERSONAL TABLES (one row-set per authenticated user)
--  Sync model: each row carries user_id = auth.uid(). The app upserts by
--  (user_id, local_id) so the same logical record updates instead of dupes.
-- ============================================================================

-- 1.1 user_settings — one row per user; the "profile + JSON sidecar"
create table if not exists public.user_settings (
  user_id       uuid primary key references auth.users(id) on delete cascade,
  name          text,
  university    text,                       -- university id (FK-by-convention to universities.id)
  absence_limit int  default 5,
  theme         text default 'dark',
  lang          text default 'en',
  avatar_url    text,
  data_blob     jsonb default '{}'::jsonb,  -- schedule, slots, absences, subjectNotes,
                                            -- gpaHistory, achievements, setupDone,
                                            -- examTimes, gradeSystem, _attSubmitted
  updated_at    timestamptz default now()
);

-- 1.2 tasks — assignments / to-dos
create table if not exists public.tasks (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  local_id     text not null,              -- client-generated stable id (Date.now based)
  name         text,
  subject      text,
  deadline     text,                        -- ISO date string
  priority     text,                        -- 'low' | 'medium' | 'high'
  completed    boolean default false,
  completed_at text,
  unique (user_id, local_id)
);

-- 1.3 exams — exam schedule (time stored in user_settings.data_blob.examTimes sidecar)
create table if not exists public.exams (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  local_id     text not null,
  subject_name text,
  date         text,                        -- ISO date string
  type         text,                        -- 'midterm' | 'final' | 'quiz'
  unique (user_id, local_id)
);

-- 1.4 subjects — GPA calculator rows
create table if not exists public.subjects (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  local_id     text not null,
  name         text,
  credits      numeric,
  score        numeric,                     -- used by percent / percent_banded / numeric_inverted systems
  letter_grade text,                        -- used by letter systems (US/Turkey)
  unique (user_id, local_id)
);

-- 1.5 study_sessions — Pomodoro / study-time log (insert-only, no local_id)
create table if not exists public.study_sessions (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references auth.users(id) on delete cascade,
  subject_name     text default 'General',
  duration_minutes integer,
  date             text                     -- ISO date string
);

-- --- RLS for personal tables: a user sees/writes ONLY their own rows ---------
alter table public.user_settings  enable row level security;
alter table public.tasks          enable row level security;
alter table public.exams          enable row level security;
alter table public.subjects       enable row level security;
alter table public.study_sessions enable row level security;

-- Helper: drop-then-create so this script is re-runnable.
do $$
declare t text;
begin
  foreach t in array array['user_settings','tasks','exams','subjects','study_sessions']
  loop
    execute format('drop policy if exists %I on public.%I', t||'_own_all', t);
    execute format(
      'create policy %I on public.%I for all to authenticated
         using (user_id = auth.uid()) with check (user_id = auth.uid())',
      t||'_own_all', t);
  end loop;
end $$;

-- [FIX 3] Co-member profile visibility -----------------------------------------
-- The app's group roster (fetchGroupBundle) and chat name lookups read other
-- members' display names. The own-row policy above forbids that, so names came
-- back null for everyone but yourself. RLS is row-level, not column-level, so a
-- naive "co-members can read user_settings" policy would also leak data_blob
-- (GPA history, absences, …). Instead we expose ONLY the safe columns through a
-- SECURITY DEFINER view whose WHERE clause restricts rows to co-members + self.

-- "Does the current user share at least one group with `other`?"  SECURITY
-- DEFINER so its internal read of group_members is not subject to the caller's
-- RLS (and never recurses, same trick as is_group_member).
create or replace function public.shares_group_with(other uuid)
returns boolean language sql security definer stable set search_path = public as $$
  select exists(
    select 1
    from group_members a
    join group_members b on a.group_id = b.group_id
    where a.user_id = auth.uid()
      and b.user_id = other
  );
$$;

-- Read-only directory of public profile fields. security_invoker is OFF
-- (definer semantics) so the view bypasses user_settings RLS, but the WHERE
-- clause limits visible rows to the caller's co-members (or the caller). Only
-- user_id, name and avatar_url are projected — data_blob never leaves the row.
drop view if exists public.member_directory;
create view public.member_directory
  with (security_invoker = off) as
  select user_id, name, avatar_url
  from public.user_settings
  where user_id = auth.uid() or public.shares_group_with(user_id);

grant select on public.member_directory to authenticated;


-- ============================================================================
--  SECTION 2 — UNIVERSITIES CATALOG (data-driven, shared + user-submitted)
--  Official rows (is_official=true) are visible to everyone. User-submitted
--  rows (is_official=false) are private to their creator (anti-spam) until an
--  admin promotes them. Grade-system LOGIC lives in JS (GRADE_SYSTEMS); this
--  table only stores which system id each university uses.
-- ============================================================================
create table if not exists public.universities (
  id                text primary key,        -- official: 'latakia','tr_itu','uk_oxford','de_tum',…
                                              -- user-added: 'user_<uid8>_<base36ts>'
  name              text not null,            -- English display name
  name_ar           text,                     -- optional Arabic display name
  country           text not null default 'SY',  -- ISO-2: SY, TR, GB, DE, …
  grade_system      text not null default 'sy_percent',  -- key into JS GRADE_SYSTEMS
  schedule_template jsonb not null default '[]'::jsonb,   -- [{start:'08:00',end:'10:00'}, …]
  is_official       boolean not null default false,       -- true = curated, visible to all
  created_by        uuid references auth.users(id) on delete set null,  -- null for official
  created_at        timestamptz not null default now()
);

alter table public.universities enable row level security;

-- SELECT: official rows OR your own submissions
drop policy if exists uni_select_official_or_own on public.universities;
create policy uni_select_official_or_own on public.universities
  for select to authenticated
  using (is_official = true or created_by = auth.uid());

-- INSERT: only your own, and never self-promoted to official
drop policy if exists uni_insert_own on public.universities;
create policy uni_insert_own on public.universities
  for insert to authenticated
  with check (created_by = auth.uid() and is_official = false);

-- UPDATE: only your own non-official rows; cannot flip to official
drop policy if exists uni_update_own on public.universities;
create policy uni_update_own on public.universities
  for update to authenticated
  using (created_by = auth.uid() and is_official = false)
  with check (created_by = auth.uid() and is_official = false);

-- DELETE: only your own non-official rows
drop policy if exists uni_delete_own on public.universities;
create policy uni_delete_own on public.universities
  for delete to authenticated
  using (created_by = auth.uid() and is_official = false);

-- --- Seed: official universities (4 countries) -------------------------------
insert into public.universities (id, name, name_ar, country, grade_system, schedule_template, is_official, created_by) values
  -- Syria (sy_percent) — timings match the app's built-in UNI_SLOTS
  ('latakia','University of Lattakia','جامعة اللاذقية','SY','sy_percent',
    '[{"start":"08:00","end":"10:00"},{"start":"10:00","end":"12:00"},{"start":"12:00","end":"14:00"},{"start":"14:00","end":"16:00"},{"start":"16:00","end":"18:00"}]', true, null),
  ('sham','Al-Sham Private University','جامعة الشام الخاصة','SY','sy_percent',
    '[{"start":"08:00","end":"10:00"},{"start":"10:00","end":"12:00"},{"start":"12:00","end":"14:00"},{"start":"14:00","end":"16:00"}]', true, null),
  ('aast','Arab Academy for Science, Technology and Maritime Transport','الأكاديمية العربية للعلوم والتكنولوجيا والنقل البحري','SY','sy_percent',
    '[{"start":"09:00","end":"10:30"},{"start":"10:30","end":"12:00"},{"start":"12:00","end":"13:30"},{"start":"13:30","end":"15:00"},{"start":"15:00","end":"16:30"}]', true, null),
  ('manara','Al-Manara University','جامعة المنارة','SY','sy_percent',
    '[{"start":"08:00","end":"10:00"},{"start":"10:00","end":"12:00"},{"start":"12:00","end":"14:00"},{"start":"14:00","end":"16:00"}]', true, null),
  ('gemtq','GEMTQ — Syrian Academy for Maritime Training','جيمتك — الأكاديمية السورية للتدريب البحري','SY','sy_percent',
    '[{"start":"09:00","end":"11:00"},{"start":"11:00","end":"13:00"},{"start":"14:00","end":"16:00"}]', true, null),
  -- Turkey (tr_absolute is the catalog tag; the JS letter system is tr_4)
  ('tr_itu','Istanbul Technical University','جامعة إسطنبول التقنية','TR','tr_absolute',
    '[{"start":"08:30","end":"10:00"},{"start":"10:00","end":"11:30"},{"start":"13:00","end":"14:30"},{"start":"14:30","end":"16:00"}]', true, null),
  ('tr_metu','Middle East Technical University (METU)','جامعة الشرق الأوسط التقنية','TR','tr_absolute',
    '[{"start":"08:40","end":"09:30"},{"start":"09:40","end":"10:30"},{"start":"10:40","end":"11:30"},{"start":"13:40","end":"14:30"},{"start":"14:40","end":"15:30"}]', true, null),
  ('tr_boun','Boğaziçi University','جامعة بوغازيتشي','TR','tr_absolute',
    '[{"start":"09:00","end":"10:00"},{"start":"10:00","end":"11:00"},{"start":"12:00","end":"13:00"},{"start":"13:00","end":"14:00"}]', true, null),
  ('tr_generic','Other Turkish University','جامعة تركية أخرى','TR','tr_absolute',
    '[{"start":"09:00","end":"10:30"},{"start":"10:30","end":"12:00"},{"start":"13:00","end":"14:30"},{"start":"14:30","end":"16:00"}]', true, null),
  -- United Kingdom (uk_honours)
  ('uk_oxford','University of Oxford','جامعة أكسفورد','GB','uk_honours',
    '[{"start":"09:00","end":"10:00"},{"start":"10:00","end":"11:00"},{"start":"11:00","end":"12:00"},{"start":"14:00","end":"15:00"},{"start":"15:00","end":"16:00"}]', true, null),
  ('uk_manchester','University of Manchester','جامعة مانشستر','GB','uk_honours',
    '[{"start":"09:00","end":"10:00"},{"start":"10:00","end":"11:00"},{"start":"11:00","end":"12:00"},{"start":"13:00","end":"14:00"},{"start":"14:00","end":"15:00"},{"start":"15:00","end":"16:00"}]', true, null),
  ('uk_ucl','University College London (UCL)','يونيفرسيتي كوليدج لندن','GB','uk_honours',
    '[{"start":"09:00","end":"11:00"},{"start":"11:00","end":"13:00"},{"start":"14:00","end":"16:00"},{"start":"16:00","end":"18:00"}]', true, null),
  ('uk_generic','Other UK University','جامعة بريطانية أخرى','GB','uk_honours',
    '[{"start":"09:00","end":"10:00"},{"start":"10:00","end":"11:00"},{"start":"11:00","end":"12:00"},{"start":"13:00","end":"14:00"},{"start":"14:00","end":"15:00"}]', true, null),
  -- Germany (de_1_5, inverted)
  ('de_tum','Technical University of Munich (TUM)','جامعة ميونخ التقنية','DE','de_1_5',
    '[{"start":"08:00","end":"09:30"},{"start":"10:00","end":"11:30"},{"start":"12:00","end":"13:30"},{"start":"14:00","end":"15:30"},{"start":"16:00","end":"17:30"}]', true, null),
  ('de_heidelberg','Heidelberg University','جامعة هايدلبرغ','DE','de_1_5',
    '[{"start":"08:15","end":"09:45"},{"start":"10:15","end":"11:45"},{"start":"12:15","end":"13:45"},{"start":"14:15","end":"15:45"}]', true, null),
  ('de_lmu','LMU Munich','جامعة ميونخ','DE','de_1_5',
    '[{"start":"08:00","end":"10:00"},{"start":"10:00","end":"12:00"},{"start":"12:00","end":"14:00"},{"start":"14:00","end":"16:00"}]', true, null),
  ('de_generic','Other German University','جامعة ألمانية أخرى','DE','de_1_5',
    '[{"start":"08:00","end":"09:30"},{"start":"10:00","end":"11:30"},{"start":"12:00","end":"13:30"},{"start":"14:00","end":"15:30"}]', true, null)
on conflict (id) do update set
  name=excluded.name, name_ar=excluded.name_ar, country=excluded.country,
  grade_system=excluded.grade_system, schedule_template=excluded.schedule_template,
  is_official=excluded.is_official;


-- ============================================================================
--  SECTION 3 — GROUPS (collaborative: shared schedule, exams, notes, chat)
--  Access is mediated by SECURITY DEFINER helper functions + RPCs (Section 4)
--  to avoid recursive RLS. The tables and their RLS shape are below.
-- ============================================================================

-- 3.1 groups — the group itself
create table if not exists public.groups (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  description   text,
  invite_code   text unique not null,
  owner_id      uuid not null references auth.users(id) on delete cascade,
  group_picture text,                        -- data-URL set via update_group_picture RPC
  chat_mode     text default 'all',          -- 'all' | 'admins' (who can post)
  time_slots    jsonb default '[]'::jsonb,    -- shared timetable slots
  created_at    timestamptz default now()
);

-- [FIX 5] Column-name drift: earlier revisions of this reference file called the
-- column picture_url, but the client (index.html) reads/writes group_picture
-- everywhere and the live update_group_picture RPC takes p_picture — the live
-- column is group_picture. If a database was ever created from the old file,
-- rename it to match the client. No-op on the live project.
do $$ begin
  if exists (select 1 from information_schema.columns
             where table_schema='public' and table_name='groups' and column_name='picture_url')
     and not exists (select 1 from information_schema.columns
             where table_schema='public' and table_name='groups' and column_name='group_picture')
  then
    alter table public.groups rename column picture_url to group_picture;
  end if;
end $$;

-- 3.2 group_members — membership + role
create table if not exists public.group_members (
  group_id  uuid not null references public.groups(id) on delete cascade,
  user_id   uuid not null references auth.users(id) on delete cascade,
  role      text not null default 'member', -- 'admin' | 'member'
  joined_at timestamptz default now(),
  primary key (group_id, user_id)
);

-- 3.3 group_shared_schedule — shared timetable cells (keyed by day + slot)
create table if not exists public.group_shared_schedule (
  group_id   uuid not null references public.groups(id) on delete cascade,
  day        text not null,                 -- e.g. 'Saturday'
  slot_key   text not null,                 -- client slot identifier
  subject    text,
  type       text,                          -- 'theoretical' | 'practical'
  professor  text,
  room       text,
  updated_at timestamptz default now(),
  primary key (group_id, day, slot_key)
);

-- 3.4 group_shared_exams — shared exams
create table if not exists public.group_shared_exams (
  id         bigint generated by default as identity primary key,
  group_id   uuid not null references public.groups(id) on delete cascade,
  local_id   text not null,
  subject    text,
  date       text,
  type       text,
  created_by uuid references auth.users(id) on delete set null,
  unique (group_id, local_id)
);

-- 3.5 group_subject_notes — one shared note per subject
create table if not exists public.group_subject_notes (
  group_id        uuid not null references public.groups(id) on delete cascade,
  subject_name    text not null,
  content         text,
  last_updated_by uuid references auth.users(id) on delete set null,
  last_updated_at timestamptz default now(),
  primary key (group_id, subject_name)
);

-- 3.6 group_messages — group chat (text + file attachments + replies)
create table if not exists public.group_messages (
  id            bigint generated by default as identity primary key,
  group_id      uuid not null references public.groups(id) on delete cascade,
  sender_id     uuid not null references auth.users(id) on delete cascade,
  sender_name   text,
  sender_avatar text,
  content       text,
  file_url      text,
  file_name     text,
  file_type     text,
  file_size     bigint,
  reply_to      bigint,                      -- references group_messages.id (soft)
  deleted       boolean default false,
  edited_at     timestamptz,
  created_at    timestamptz default now()
);

-- --- group indexes (chat + lookups) ------------------------------------------
create index if not exists idx_group_messages_group_created on public.group_messages(group_id, created_at);
create index if not exists idx_group_members_user on public.group_members(user_id);

-- --- SECURITY DEFINER helpers (break RLS recursion) --------------------------
-- These already exist in your project. Recreated here because their bodies are
-- short and known; safe to "create or replace".
create or replace function public.is_group_member(gid uuid)
returns boolean language sql security definer stable set search_path = public as $$
  select exists(select 1 from group_members where group_id = gid and user_id = auth.uid());
$$;

create or replace function public.is_group_admin(gid uuid)
returns boolean language sql security definer stable set search_path = public as $$
  select exists(select 1 from group_members
                where group_id = gid and user_id = auth.uid() and role = 'admin');
$$;

-- [FIX 4] "May the current user post in this group right now?"  Honours
-- groups.chat_mode: everyone may post when 'all', only admins when 'admins'.
-- SECURITY DEFINER so the internal reads of groups/group_members ignore the
-- caller's RLS. Used by the message INSERT policy below so the chat-mode lock
-- is enforced at the DB layer, not just hidden in the UI.
create or replace function public.can_post_in_group(gid uuid)
returns boolean language sql security definer stable set search_path = public as $$
  select exists(
    select 1
    from groups g
    join group_members m on m.group_id = g.id
    where g.id = gid
      and m.user_id = auth.uid()
      and (g.chat_mode is distinct from 'admins' or m.role = 'admin')
  );
$$;

-- --- Groups RLS --------------------------------------------------------------
alter table public.groups                enable row level security;
alter table public.group_members         enable row level security;
alter table public.group_shared_schedule enable row level security;
alter table public.group_shared_exams    enable row level security;
alter table public.group_subject_notes   enable row level security;
alter table public.group_messages        enable row level security;

-- groups: members can read; only owner/admin mutate via RPCs (see Section 4).
drop policy if exists grp_select_member on public.groups;
create policy grp_select_member on public.groups
  for select to authenticated using (is_group_member(id));

-- group_members: a member can see the roster of their groups.
drop policy if exists gm_select_member on public.group_members;
create policy gm_select_member on public.group_members
  for select to authenticated using (is_group_member(group_id));

-- [FIX 2] group_members: a user may remove THEMSELVES (leaveGroup does a direct
-- delete). Without this, RLS denied the delete silently (0 rows, no error) and
-- the user stayed a member server-side. Adding/kicking still go through the
-- SECURITY DEFINER RPCs, so this self-delete is the only direct write allowed.
drop policy if exists gm_delete_self on public.group_members;
create policy gm_delete_self on public.group_members
  for delete to authenticated using (user_id = auth.uid());

-- Shared schedule / exams: members read; admins write.
do $$
declare t text;
begin
  foreach t in array array['group_shared_schedule','group_shared_exams']
  loop
    execute format('drop policy if exists %I on public.%I', t||'_sel', t);
    execute format('create policy %I on public.%I for select to authenticated using (is_group_member(group_id))', t||'_sel', t);
    execute format('drop policy if exists %I on public.%I', t||'_write', t);
    execute format('create policy %I on public.%I for all to authenticated using (is_group_admin(group_id)) with check (is_group_admin(group_id))', t||'_write', t);
  end loop;
end $$;

-- [FIX 1] group_subject_notes: collaborative notes — ANY member reads AND
-- writes (the app's upsertGroupNote is documented "any member"). Previously
-- this table shared the admin-only write policy with schedule/exams above,
-- which made every non-admin note save fail the WITH CHECK.
drop policy if exists group_subject_notes_sel on public.group_subject_notes;
create policy group_subject_notes_sel on public.group_subject_notes
  for select to authenticated using (is_group_member(group_id));

drop policy if exists group_subject_notes_write on public.group_subject_notes;
create policy group_subject_notes_write on public.group_subject_notes
  for all to authenticated
  using (is_group_member(group_id)) with check (is_group_member(group_id));

-- group_messages: members read; sender inserts own (honouring chat_mode);
-- sender (or admin) edits/deletes.
drop policy if exists msg_select_member on public.group_messages;
create policy msg_select_member on public.group_messages
  for select to authenticated using (is_group_member(group_id));

-- [FIX 4] insert now requires can_post_in_group() so 'admins'-only chat is
-- enforced in the database, not merely greyed-out in the client.
drop policy if exists msg_insert_own on public.group_messages;
create policy msg_insert_own on public.group_messages
  for insert to authenticated
  with check (sender_id = auth.uid() and can_post_in_group(group_id));

drop policy if exists msg_update_own_or_admin on public.group_messages;
create policy msg_update_own_or_admin on public.group_messages
  for update to authenticated
  using (sender_id = auth.uid() or is_group_admin(group_id));


-- ============================================================================
--  SECTION 4 — GROUP RPC FUNCTIONS  ⚠️ SIGNATURES ONLY — NOT REPRODUCED HERE
--  These are SECURITY DEFINER functions whose full bodies live ONLY in your
--  Supabase project (not in the app code), so this file cannot faithfully
--  recreate them. They are listed so the data model is complete. If you ever
--  need to rebuild them, ask the assistant to write them from this behaviour
--  spec — do NOT assume running this file restored them.
--
--    create_group(p_name text, p_description text) -> groups row
--        Creates a group, generates a unique invite_code, inserts the caller
--        into group_members as 'admin'/owner.
--    join_group_by_code(p_code text) -> groups row
--        Looks up a group by invite_code; inserts caller as 'member'.
--    my_group() -> groups row (+ membership)
--        Returns the caller's current group (the app supports one active group).
--    delete_group(p_group_id uuid) -> void          [owner only]
--    kick_group_member(p_group_id uuid, p_user_id uuid) -> void   [admin only]
--    rotate_group_invite_code(p_group_id uuid) -> text            [admin only]
--    update_group_name(p_group_id uuid, p_name text) -> void      [admin only]
--    update_group_description(p_group_id uuid, p_description text) -> void
--    update_group_picture(p_group_id uuid, p_picture text) -> void  [admin only]
--    update_group_chat_mode(p_group_id uuid, p_mode text) -> void [admin only]
--    update_group_time_slots(p_group_id uuid, p_slots jsonb) -> void [admin only]
--
--  (All enforce owner/admin checks internally via is_group_admin / owner_id.)
-- ============================================================================


-- ============================================================================
--  SECTION 5 — STORAGE (Supabase Storage bucket for chat attachments)
--  Bucket: 'group-files' (or your chosen name). Created via the Storage UI,
--  not SQL. Policies allow group members to read; senders to upload. If you
--  need exact storage.objects policies regenerated, ask the assistant.
-- ============================================================================


-- ============================================================================
--  SECTION 6 — RLS AUDIT NOTES (2026-06-05)
--  Full review of every policy above against the app's actual data access in
--  index.html. No two policies contradict each other (all are PERMISSIVE and
--  scoped TO authenticated, so they OR-combine — there is no restrictive/
--  permissive AND-conflict). The four issues below were code-vs-policy
--  mismatches where the app asked for something RLS refused; each is fixed
--  inline above and tagged [FIX n].
--
--  [FIX 1] group_subject_notes write was admin-only but upsertGroupNote()
--          (index.html) lets any member edit -> non-admin saves were rejected.
--          Now member-writable.
--  [FIX 2] group_members had only a SELECT policy; leaveGroup() deletes the
--          caller's own row directly -> RLS denied it silently (0 rows, no
--          error), so users never really left. Added gm_delete_self.
--  [FIX 3] Roster/name lookups read other users' user_settings, but the
--          own-row policy returned null for everyone else. Added the
--          member_directory view (+ shares_group_with helper) exposing only
--          user_id/name/avatar_url to co-members. The app reads names from
--          this view now (index.html: fetchGroupBundle + fetchMemberNames).
--  [FIX 4] groups.chat_mode='admins' was UI-only; msg_insert_own checked only
--          membership. Added can_post_in_group() to the insert WITH CHECK so
--          the lock holds at the DB layer.
--  [FIX 5] (2026-06-10) groups.picture_url renamed to group_picture: the client
--          uses group_picture in all 11 call sites and passes p_picture to the
--          working update_group_picture RPC, so the old picture_url name in
--          this reference file was a transcription error. Conditional rename
--          added after the table definition (no-op on the live project).
--
--  Verified consistent (no change needed): personal tables own_all; the four
--  universities command-split policies; grp_select_member + RPC-only group
--  mutations; admin-only writes on shared schedule/exams matching the app's
--  admin-gated calls; msg_update_own_or_admin vs soft-delete; study_sessions
--  insert-only. Note: official universities are visible to AUTHENTICATED users
--  only (not anon) — the app is auth-gated with a built-in fallback, so this is
--  intentional even though the prose says "everyone".
-- ============================================================================


-- ============================================================================
--  QUICK SANITY CHECKS (run after applying)
-- ============================================================================
-- Tables present (expect 12):
--   select table_name from information_schema.tables
--   where table_schema='public' order by table_name;
-- Universities catalog spans 4 countries:
--   select country, count(*) from public.universities group by country order by country;
-- Policies on universities (expect 4: select/insert/update/delete):
--   select policyname, cmd from pg_policies where tablename='universities';
-- group_members policies (expect 2: gm_select_member, gm_delete_self):
--   select policyname, cmd from pg_policies where tablename='group_members';
-- Co-member directory returns names (run as an authenticated user in a group):
--   select * from public.member_directory;
